### ISSUE TITLE
[bug] mailto parameter when calling CrossRef

### ISSUE THREAD

**Issue by smierz** [sneakers-the-rat/paper-feeds#29]
There are two issues with getting into the polite pool of CrossRef:
* the `mailto` parameter is currently never set. since `get_crossref` is basically a private method, the parameter would have to be added to every public method (e.g. `journal_search`, `fetch_paper_page`). could be improved by making it an object where the parameter is set once at creation.
* the `contact` parameter for `get_crossref` has the wrong type (-> `Config`). If you would hand over your config to the method the `mailto` parameter would be something like `db=PosixPath('db.sqlite') log_dir=PosixPath('logs') host='localhost' port=8000 env='dev' crossref_email=None public_url='http://localhost'`

**Comment by sneakers-the-rat** [comment]
oop you're very right, missed that - had already made the config parameter and everything.

config is sourced from a .env file or environment variables, have documenting how that works on the checklist!

https://github.com/sneakers-the-rat/paper-feeds/pull/30
